const data = {
  products: [
    {
      id: 1,
      name: 'Product 1',
      price: '1.00',
      category: 'Category 1',
      description: 'Description 1',
      image: 'https://picsum.photos/200/300/?random',
      brand: 'Brand 1',
      rating: '4.5',
      numReviews: '10',
      stock: '10',
    },
    {
      id: 2,
      name: 'Product 2',
      price: '2.00',
      category: 'Category 2',
      description: 'Description 2',
      image: 'https://picsum.photos/200/300/?random',
      brand: 'Brand 2',
      rating: '2.5',
      numReviews: '1',
      stock: '100',
    },
    {
      id: 3,
      name: 'Product 3',
      price: '14.00',
      category: 'Category 3',
      description: 'Description 3',
      image: 'https://picsum.photos/200/300/?random',
      brand: 'Brand 2',
      rating: '1.5',
      numReviews: '1',
      stock: '0',
    },
    {
      id: 4,
      name: 'Product 4',
      price: '80.90',
      category: 'Category 4',
      description: 'Description 4',
      image: 'https://picsum.photos/200/300/?random',
      brand: 'Brand 3',
      rating: '4.9',
      numReviews: '60',
      stock: '8',
    },
    {
      id: 5,
      name: 'Product 5',
      price: '180.00',
      category: 'Category 5',
      description: 'Description 5',
      image: 'https://picsum.photos/200/300/?random',
      brand: 'Brand 1',
      rating: '4.0',
      numReviews: '2',
      stock: '100',
    },
  ],
};

export default data;
